Add Metabiome's welcoming
Nesper94/Metabiome pull request #51
Opened 2021-06-02 03:25 UTC by biocdgv

Hi Guys!! 

I have taken some risks and have created a new look for Metabiome's main script. Do you think is too much? I like it but I wanna know if you both like it too!! It is just a proposal!! I have made it through here [doodles](http://patorjk.com/software/taag/#p=display&v=2&f=ANSI%20Shadow&t=METABIOME%0A).

The changes are as follows: 

- Add Metabiome's bold welcoming to Metabiome main script
- Add issues' recommendation at the end of Metabiome main script

:broccoli: :broccoli: :broccoli: :broccoli: :broccoli: :broccoli: :broccoli:

2021-06-02 03:58 UTC, Nesper94 requested changes
Hi! Looks very nice! :sauropod:  Here some suggestions:

2021-06-02 03:58 UTC, Nesper94 commented on scripts/metabiome.sh
Remove one blank line:
```suggestion
```

2021-06-02 03:58 UTC, Nesper94 commented on scripts/metabiome.sh
> +
Tabs should be replaced with spaces. Line length should be of max 80 chars, as it does not look fine on terminals with default size:
![Selection_001](https://user-images.githubusercontent.com/63323077/120421558-24e69280-c32c-11eb-9103-22b6660e682b.png)

2021-06-02 03:58 UTC, Nesper94 commented on scripts/metabiome.sh
> +github (https://github.com/Nesper94/Metabiome)
Same line length suggestion:
```suggestion
If you are having problems running Metabiome, please do not hesitate to
contact us through GitHub (https://github.com/Nesper94/Metabiome)
```

2021-06-04 17:54 UTC, Estefany-Lorenzana submitted a review, later dismissed
Hi guys! It looks really good! What do you think about add in help function some welcome like this but smaller and with the name of the tool to us?

2021-06-07 19:02 UTC, biocdgv commented on scripts/metabiome.sh
> +				Welcome to:
Indeed juan!! i will do it asap.

2021-06-07 19:18 UTC, biocdgv commented
> Hi guys! It looks really good! What do you think about add in help function some welcome like this but smaller and with the name of the tool to us?

Hellow Stefa!! Do you mean adding to, for example, bowtie2, the same welcome as Metabiome? Like the following but smaller

![imagen](https://user-images.githubusercontent.com/57162811/121075476-d8231180-c79a-11eb-9355-543e9c571e64.png)

Also, I haven't been able to reduce the font size of the Metabiome's welcoming...dunno if it's possible...

:wrench:

2021-06-08 01:30 UTC, Nesper94 approved these changes
It is great! I will also think in a way to implement the @Estefany-Lorenzana's proposal.

2021-06-09 03:45 UTC, Estefany-Lorenzana commented
> > Hi guys! It looks really good! What do you think about add in help function some welcome like this but smaller and with the name of the tool to us?
> 
> Hellow Stefa!! Do you mean adding to, for example, bowtie2, the same welcome as Metabiome? Like the following but smaller
> 
> ![imagen](https://user-images.githubusercontent.com/57162811/121075476-d8231180-c79a-11eb-9355-543e9c571e64.png)
> 
> Also, I haven't been able to reduce the font size of the Metabiome's welcoming...dunno if it's possible...
> 
> wrench

Hi! Yeah, that's what I think!

2021-06-09 03:45 UTC, Estefany-Lorenzana approved these changes

2021-06-09 23:53 UTC, merged