Complete README
Nesper94/Metabiome pull request #53
Opened 2021-06-17 00:31 UTC by biocdgv

Add some changes to Metabiome's README:

- Add badges
- Add binning section.
- Add the following sections: basic usage, ask for help, contribution and acknowledgments.

Also, remove unnecessary "" in Kraken2 usage function output.

2021-06-17 00:45 UTC, Nesper94 requested changes

2021-06-17 00:45 UTC, Nesper94 commented on README.md
> +)
Remover paréntesis que sobra:
```suggestion

```

2021-06-17 00:45 UTC, Nesper94 commented on README.md
> +Juan Camilo Arboleda: juan.arboleda2@udea.edu.co
```suggestion
[Cristian Grisales-Vargas](mailto:cristian.grisales@udea.edu.co)  
[Estefany Lorenzana](mailto:estefany.lorenzana@udea.edu.co)  
[Juan Camilo Arboleda](mailto:juan.arboleda2@udea.edu.co)  
```

2021-06-17 00:45 UTC, Nesper94 commented on README.md
> +environments to ease its use. `Metabiome` includes several features of common
```suggestion
environments to ease its use. Metabiome includes several features of common
```

2021-06-17 00:45 UTC, Nesper94 commented on README.md
> +can use with `Metabiome`.
```suggestion
can use with Metabiome.
```

2021-06-17 00:45 UTC, Nesper94 commented on README.md
> +`Metabiome` can be invoked like so:
```suggestion
Metabiome can be invoked like so:
```

2021-06-17 00:45 UTC, Nesper94 commented on README.md
> +If you want to contribute to `Metabiome`, you should fork the project.
```suggestion
If you want to contribute to Metabiome, you should fork the project.
```

2021-06-17 00:45 UTC, Nesper94 commented on README.md
> +If you have problems or suggestions regarding `Metabiome`, please submit an
```suggestion
If you have problems or suggestions regarding Metabiome, please submit an
```

2021-06-17 00:45 UTC, Nesper94 commented on README.md
> +If you have questions about how to use `Metabiome`, or are interested in
```suggestion
If you have questions about how to use Metabiome, or are interested in
```

2021-06-17 00:45 UTC, Nesper94 commented on README.md
> +There are two prerequisites for running `Metabiome`:
```suggestion
There are two prerequisites for running Metabiome:
```

2021-06-17 00:49 UTC, Estefany-Lorenzana commented on README.md
> +Juan Camilo Arboleda: juan.arboleda2@udea.edu.co
It looks better with the link!

2021-06-17 01:31 UTC, Nesper94 requested changes

2021-06-17 01:31 UTC, Nesper94 commented on README.md
> +</p>
Put logo outside paragraph and next to the title:
```suggestion
<img src="https://i.imgur.com/FGbY9Ed.png" width=120 align="left" />

# Metabiome
A flexible and modular pipeline for microbiome analysis.

[![License: MIT](https://img.shields.io/badge/License-MIT-orange.svg)](https://github.com/Nesper94/Metabiome/blob/master/LICENSE)
[![Maintained?](https://img.shields.io/badge/Maintained%3F-yes-green.svg)](https://github.com/Nesper94/Metabiome/pulse)
[![Made with: bash](https://img.shields.io/badge/Made%20with-Bash-1f425f.svg)](https://www.gnu.org/software/bash/)
[![Read: the docs](https://img.shields.io/badge/read-the%20docs-blue)](https://metabiome.readthedocs.io/en/latest/)
```

2021-06-17 02:51 UTC, Estefany-Lorenzana submitted a review, later dismissed

2021-06-24 01:09 UTC, Nesper94 approved these changes

2021-06-24 03:11 UTC, Estefany-Lorenzana approved these changes

2021-06-24 03:16 UTC, merged