Add trimmomatic's options
Nesper94/Metabiome pull request #57
Opened 2021-07-15 00:42 UTC by Estefany-Lorenzana

2021-07-15 01:55 UTC, Nesper94 requested changes

2021-07-15 01:55 UTC, Nesper94 commented on scripts/trimmomatic.sh
> +               	   will be created if it doesn't exist.
Use spaces instead of tabs in these lines.

2021-07-29 22:35 UTC, biocdgv approved these changes

2021-08-09 13:17 UTC, Nesper94 approved these changes

2021-08-12 01:15 UTC, merged